## Ejercicio en casa 2
##### Dataset de Netflix (Contenidos)
https://www.kaggle.com/datasets/swatikhedekar/exploratory-data-analysis-on-netflix-data

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("netflix_titles_2021.csv")
df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

# Ejercicio en Casa:

Para este ejercicio debes realizar los siguientes pasos de manera anticipada los siguientes procesos:
- Cargar el conjunto de datos desde un archivo CSV utilizando pandas.
- Explorar y familiarizarse con la estructura del conjunto de datos.
- Calcular estadísticas descriptivas, como el promedio, la mediana y la desviación estándar, de variables relevantes del conjunto de datos general.

#### Acciones por ejecutar

1. Explorar inconsistencias
2. Separar contenidos con duración en minutos y temporadas
3. Homogenizar para detectar preguntas como: Tiempo promedio, temporadas promedio.
4. Relación entre listed_in y duration (separado mins y temporadas)
5. Frecuencia de distribución de los paises
6. Actores principales por pais
7. Relación entre tipo y duración
8. Relación entre listed_in y tipo

In [3]:
# Exploración básica inicial
df.shape

(8807, 12)

In [5]:
# Características disponibles
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [6]:
# Tipos de cada columna
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [7]:
# información general por columna
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [8]:
# Exploración general
for col in df.columns:
    print("Columna: ", col, "[", df[col].nunique(), "]")
    print(df[col].sort_values().unique())

Columna:  show_id [ 8807 ]
['s1' 's10' 's100' ... 's997' 's998' 's999']
Columna:  type [ 2 ]
['Movie' 'TV Show']
Columna:  title [ 8807 ]
['#Alive' '#AnneFrank - Parallel Stories' '#FriendButMarried' ... '마녀사냥'
 '반드시 잡는다' '최강전사 미니특공대 : 영웅의 탄생']
Columna:  director [ 4528 ]
['A. L. Vijay' 'A. Raajdheep' 'A. Salaam' ... 'Ömer Faruk Sorak'
 'Şenol Sönmez' nan]
Columna:  cast [ 7692 ]
["'Najite Dede, Jude Chukwuka, Taiwo Arimoro, Odenike Odetola, Funmi Eko, Keppy Ekpenyong"
 '4Minute, B1A4, BtoB, ELSIE, EXID, EXO, Got7, INFINITE, KARA, Shinee, Sistar, VIXX, Nine Muses, BTS, Secret, Topp Dogg'
 '50 Cent, Ryan Phillippe, Bruce Willis, Rory Markham, Jenna Dewan, Brett Granstaff, Randy Couture, Susie Abromeit, Ron Turner, James Remar'
 ...
 'Şükrü Özyıldız, Aslı Enver, Şenay Gürler, Başak Parlak, Mahir Günşiray, Hakan Boyav, Hakan Gerçek, Berrak Kuş, Gamze Süner Atay, Mehmet Esen'
 'Ṣọpẹ́ Dìrísù, Wunmi Mosaku, Matt Smith, Malaika Wakoli-Abigaba' nan]
Columna:  country [ 748 ]
[', France, Algeria' ', South Korea' 'Argentina'
 'Argentina, Brazil, France, Poland, Germany, Denmark' 'Argentina, Chile'
 'Argentina, Chile, Peru' 'Argentina, France'
 'Argentina, France, United States, Germany, Qatar' 'Argentina, Italy'
 'Argentina, Spain' 'Argentina, United States'
 'Argentina, United States, Mexico' 'Argentina, Uruguay, Serbia'
 'Argentina, Uruguay, Spain, France' 'Argentina, Venezuela' 'Australia'
 'Australia, Armenia, Japan, Jordan, Mexico, Mongolia, New Zealand, Philippines, South Africa, Sweden, United States, Uruguay'
 'Australia, Canada' 'Australia, France' 'Australia, France, Ireland'
 'Australia, Germany' 'Australia, India' 'Australia, Iraq'
 'Australia, New Zealand' 'Australia, New Zealand, United States'
 'Australia, United Arab Emirates' 'Australia, United Kingdom'
 'Australia, United Kingdom, Canada'
 'Australia, United Kingdom, United Arab Emirates, Canada'
 'Australia, United Kingdom, United States, New Zealand, Italy, France'
 'Australia, United States' 'Austria' 'Austria, Czech Republic'
 'Austria, Germany' 'Austria, Iraq, United States'
 'Austria, United States' 'Bangladesh' 'Belarus' 'Belgium'
 'Belgium, France' 'Belgium, France, Netherlands'
 'Belgium, Ireland, Netherlands, Germany, Afghanistan'
 'Belgium, Netherlands' 'Belgium, United Kingdom'
 'Belgium, United Kingdom, United States' 'Brazil' 'Brazil, France'
 'Brazil, France, Germany' 'Brazil, India, China, United States'
 'Brazil, Netherlands, United States, Colombia, Austria, Germany'
 'Brazil, United Kingdom' 'Brazil, United States' 'Bulgaria'
 'Bulgaria, United States' 'Bulgaria, United States, Spain, Canada'
 'Cambodia' 'Cambodia, United States' 'Cameroon' 'Canada'
 'Canada, Australia' 'Canada, Belgium' 'Canada, Brazil' 'Canada, France'
 'Canada, France, Italy, Morocco, United States'
 'Canada, France, United States' 'Canada, Germany'
 'Canada, Germany, France, United States' 'Canada, Germany, South Africa'
 'Canada, Hungary, United States' 'Canada, India'
 'Canada, India, Thailand, United States, United Arab Emirates'
 'Canada, Ireland, United States' 'Canada, Japan, Netherlands'
 'Canada, Japan, United States' 'Canada, Luxembourg'
 'Canada, Mexico, Germany, South Africa' 'Canada, Nigeria'
 'Canada, Nigeria, United States' 'Canada, Norway' 'Canada, South Africa'
 'Canada, South Korea, United States' 'Canada, Spain'
 'Canada, Spain, France' 'Canada, United Kingdom'
 'Canada, United Kingdom, Netherlands'
 'Canada, United Kingdom, United States' 'Canada, United States'
 'Canada, United States, Cayman Islands' 'Canada, United States, Denmark'
 'Canada, United States, France' 'Canada, United States, Germany'
 'Canada, United States, India, United Kingdom'
 'Canada, United States, Ireland' 'Canada, United States, Mexico'
 'Canada, United States, United Kingdom'
 'Canada, United States, United Kingdom, France, Luxembourg' 'Chile'
 'Chile, Argentina' 'Chile, Argentina, France, Spain, United States'
 'Chile, Brazil' 'Chile, France' 'Chile, Italy' 'Chile, Peru'
 'Chile, Spain, Argentina, Germany' 'Chile, United States, France' 'China'
 'China, Canada, United States' 'China, Germany, India, United States'
 'China, Hong Kong' 'China, Hong Kong, United States'
 'China, India, Nepal' 'China, Japan' 'China, Morocco, Hong Kong'
 'China, South Korea, United States'
 'China, Spain, South Korea, United States' 'China, Taiwan'
 'China, United Kingdom' 'China, United States'
 'China, United States, Australia' 'China, United States, Canada'
 'China, United States, United Kingdom' 'Colombia' 'Colombia, Mexico'
 'Colombia, Mexico, United States' 'Colombia, Peru, United Kingdom'
 'Colombia, United States' 'Croatia'
 'Croatia, Slovenia, Serbia, Montenegro' 'Cyprus' 'Czech Republic, France'
 'Czech Republic, Slovakia' 'Czech Republic, United Kingdom, France'
 'Czech Republic, United Kingdom, United States'
 'Czech Republic, United States' 'Denmark'
 'Denmark, Brazil, France, Portugal, Sweden' 'Denmark, China'
 'Denmark, France, Belgium, Italy, Netherlands, United States, United Kingdom'
 'Denmark, France, Poland' 'Denmark, France, United States, Sweden'
 'Denmark, Germany, Belgium, United Kingdom, France'
 'Denmark, Germany, Belgium, United Kingdom, France, Sweden'
 'Denmark, Indonesia, Finland, Norway, United Kingdom, Israel, France, United States, Germany, Netherlands'
 'Denmark, Singapore, Canada, United States' 'Denmark, Spain'
 'Denmark, Sweden, Israel, United States'
 'Denmark, United Kingdom, South Africa, Sweden, Belgium'
 'Denmark, United Kingdom, Sweden' 'Denmark, United States'
 'Denmark, Zimbabwe' 'Egypt' 'Egypt, Algeria'
 'Egypt, Austria, United States' 'Egypt, Denmark, Germany' 'Egypt, France'
 'Egypt, Saudi Arabia' 'Finland' 'Finland, France' 'Finland, Germany'
 'Finland, Germany, Belgium' 'Finland, Sweden, Norway, Latvia, Germany'
 'Finland, United States' 'France' 'France, Algeria'
 'France, Australia, Germany' 'France, Belgium'
 'France, Belgium, China, United States' 'France, Belgium, Italy'
 'France, Belgium, Luxembourg, Cambodia,'
 'France, Belgium, Luxembourg, Romania, Canada, United States'
 'France, Belgium, Spain' 'France, Belgium, United States'
 'France, Brazil, Spain, Belgium' 'France, Canada'
 'France, Canada, Belgium' 'France, Canada, China, Cambodia'
 'France, Canada, Italy, United States, China'
 'France, Canada, United States' 'France, Canada, United States, Spain'
 'France, China, Japan, United States' 'France, Egypt' 'France, Germany'
 'France, Germany, Czech Republic, Belgium' 'France, Germany, Switzerland'
 'France, Iran, United States'
 'France, Israel, Germany, United States, United Kingdom' 'France, Japan'
 'France, Japan, United States' 'France, Lebanon'
 'France, Lebanon, United Kingdom' 'France, Luxembourg, Canada'
 'France, Luxembourg, United States' 'France, Malta, United States'
 'France, Morocco' 'France, Netherlands, Singapore'
 'France, Netherlands, South Africa, Finland' 'France, New Zealand'
 'France, Norway, Lebanon, Belgium' 'France, Qatar'
 'France, Senegal, Belgium' 'France, South Korea, Japan'
 'France, South Korea, Japan, United States'
 'France, Switzerland, Spain, United States, United Arab Emirates'
 'France, United Kingdom' 'France, United Kingdom, India'
 'France, United Kingdom, United States' 'France, United States'
 'France, United States, Canada' 'France, United States, Mexico'
 'France, United States, United Kingdom, Canada' 'Georgia'
 'Georgia, Germany, France' 'Germany' 'Germany, Australia'
 'Germany, Australia, France, China' 'Germany, Belgium'
 'Germany, Canada, United States' 'Germany, China, United Kingdom'
 'Germany, Czech Republic' 'Germany, France'
 'Germany, France, Luxembourg, United Kingdom, United States'
 'Germany, France, Russia'
 'Germany, France, United States, Canada, United Kingdom' 'Germany, Italy'
 'Germany, Jordan, Netherlands' 'Germany, Sri Lanka'
 'Germany, United Kingdom' 'Germany, United Kingdom, United States'
 'Germany, United States' 'Germany, United States, Canada'
 'Germany, United States, France'
 'Germany, United States, Hong Kong, Singapore'
 'Germany, United States, Italy' 'Germany, United States, Sweden'
 'Germany, United States, United Kingdom, Canada' 'Ghana'
 'Ghana, United States' 'Greece, United States' 'Guatemala' 'Hong Kong'
 'Hong Kong, Canada, United States' 'Hong Kong, China'
 'Hong Kong, China, Singapore' 'Hong Kong, China, United States'
 'Hong Kong, Iceland, United States' 'Hong Kong, Taiwan'
 'Hong Kong, United States' 'Hungary' 'Hungary, United States' 'Iceland'
 'Iceland, Sweden, Belgium' 'India' 'India, Australia' 'India, Canada'
 'India, France' 'India, Germany' 'India, Germany, Austria'
 'India, Germany, France' 'India, Iran' 'India, Japan' 'India, Malaysia'
 'India, Mexico' 'India, Nepal' 'India, Pakistan' 'India, Soviet Union'
 'India, Switzerland' 'India, Turkey' 'India, United Kingdom'
 'India, United Kingdom, Canada, United States'
 'India, United Kingdom, China, Canada, Japan, South Korea, United States'
 'India, United Kingdom, France, Qatar' 'India, United States' 'Indonesia'
 'Indonesia, Netherlands' 'Indonesia, Singapore'
 'Indonesia, South Korea, Singapore' 'Indonesia, United Kingdom'
 'Indonesia, United States' 'Iran, France' 'Ireland' 'Ireland, Canada'
 'Ireland, Canada, Luxembourg, United States, United Kingdom, Philippines, India'
 'Ireland, Canada, United Kingdom, United States'
 'Ireland, Canada, United States, United Kingdom'
 'Ireland, France, Iceland, United States, Mexico, Belgium, United Kingdom, Hong Kong'
 'Ireland, Luxembourg, Belgium' 'Ireland, South Africa'
 'Ireland, Switzerland, United Kingdom, France, United States'
 'Ireland, United Kingdom' 'Ireland, United Kingdom, France, Germany'
 'Ireland, United Kingdom, Greece, France, Netherlands'
 'Ireland, United Kingdom, Italy, United States'
 'Ireland, United Kingdom, United States' 'Ireland, United States'
 'Ireland, United States, France' 'Ireland, United States, United Kingdom'
 'Israel' 'Israel, Germany' 'Israel, Germany, France'
 'Israel, Germany, Poland, Luxembourg, Belgium, France, United States'
 'Israel, Sweden, Germany, Netherlands' 'Israel, United States' 'Italy'
 'Italy, Belgium' 'Italy, Brazil, Greece' 'Italy, Canada, France'
 'Italy, France' 'Italy, France, Switzerland' 'Italy, Germany'
 'Italy, India'
 'Italy, South Africa, West Germany, Australia, United States'
 'Italy, Switzerland, Albania, Poland'
 'Italy, Switzerland, France, Germany' 'Italy, Turkey'
 'Italy, United Kingdom' 'Italy, United Kingdom, France'
 'Italy, United States' 'Italy, United States, Argentina'
 'Jamaica, United States' 'Japan' 'Japan, Canada'
 'Japan, Canada, United States' 'Japan, United States' 'Jordan' 'Kenya'
 'Kenya, United States' 'Kuwait' 'Kuwait, United States' 'Lebanon'
 'Lebanon, Canada, France' 'Lebanon, France'
 'Lebanon, Palestine, Denmark, Qatar' 'Lebanon, Qatar' 'Lebanon, Syria'
 'Lebanon, United Arab Emirates'
 'Lebanon, United Arab Emirates, France, Switzerland, Germany'
 'Lebanon, United States, United Arab Emirates' 'Luxembourg' 'Malaysia'
 'Malaysia, Singapore, Hong Kong' 'Mauritius' 'Mauritius, South Africa'
 'Mexico' 'Mexico, Argentina' 'Mexico, Brazil' 'Mexico, Finland'
 'Mexico, France' 'Mexico, France, Colombia' 'Mexico, Netherlands'
 'Mexico, Spain' 'Mexico, United States'
 'Mexico, United States, Spain, Colombia' 'Mozambique' 'Namibia'
 'Netherlands' 'Netherlands, Belgium'
 'Netherlands, Belgium, Germany, Jordan'
 'Netherlands, Belgium, United Kingdom, United States'
 'Netherlands, Denmark, France, Germany'
 'Netherlands, Denmark, South Africa'
 'Netherlands, Germany, Denmark, United Kingdom'
 'Netherlands, Germany, Italy, Canada' 'Netherlands, United States'
 'New Zealand' 'New Zealand, Australia, France, United States'
 'New Zealand, United Kingdom' 'New Zealand, United Kingdom, Australia'
 'New Zealand, United States' 'Nigeria' 'Nigeria, United Kingdom' 'Norway'
 'Norway, Denmark' 'Norway, Denmark, Netherlands, Sweden'
 'Norway, Denmark, Sweden' 'Norway, Germany' 'Norway, Germany, Sweden'
 'Norway, Iceland, United States' 'Norway, Sweden'
 'Norway, United Kingdom, France, Ireland' 'Norway, United States'
 'Pakistan' 'Pakistan, Norway, United States'
 'Pakistan, United Arab Emirates' 'Pakistan, United States'
 'Paraguay, Argentina' 'Peru' 'Peru, Germany, Norway'
 'Peru, United States, United Kingdom' 'Philippines'
 'Philippines, Canada, United Kingdom, United States' 'Philippines, Qatar'
 'Philippines, Singapore' 'Philippines, Singapore, Indonesia'
 'Philippines, United States' 'Poland' 'Poland,' 'Poland, United States'
 'Poland, West Germany' 'Portugal, France, Poland, United States'
 'Portugal, Spain' 'Portugal, United States'
 'Puerto Rico, United States, Colombia' 'Romania'
 'Romania, Bulgaria, Hungary' 'Romania, France, Switzerland, Germany'
 'Romania, United Kingdom' 'Romania, United States' 'Russia'
 'Russia, Poland, Serbia' 'Russia, Spain' 'Russia, United States'
 'Russia, United States, China' 'Saudi Arabia'
 'Saudi Arabia, Netherlands, Germany, Jordan, United Arab Emirates, United States'
 'Saudi Arabia, Syria, Egypt, Lebanon, Kuwait'
 'Saudi Arabia, United Arab Emirates' 'Senegal'
 'Serbia, South Korea, Slovenia' 'Serbia, United States' 'Singapore'
 'Singapore, France' 'Singapore, Japan, France' 'Singapore, Malaysia'
 'Singapore, United States'
 'Slovenia, Croatia, Germany, Czech Republic, Qatar'
 'Somalia, Kenya, Sudan, South Africa, United States' 'South Africa'
 'South Africa, Angola' 'South Africa, China, United States'
 'South Africa, Germany, Netherlands, France' 'South Africa, Nigeria'
 'South Africa, United States' 'South Africa, United States, Germany'
 'South Africa, United States, Japan'
 'South Africa, United States, New Zealand, Canada' 'South Korea'
 'South Korea, Canada, United States, China' 'South Korea, China'
 'South Korea, China, United States' 'South Korea, Czech Republic'
 'South Korea, France' 'South Korea, Japan' 'South Korea, United States'
 'Soviet Union, India' 'Spain' 'Spain, Argentina' 'Spain, Belgium'
 'Spain, Belgium, United States' 'Spain, Canada, United States'
 'Spain, Colombia' 'Spain, Cuba' 'Spain, France' 'Spain, France, Canada'
 'Spain, France, Canada, United States' 'Spain, France, Italy'
 'Spain, France, United Kingdom, United States'
 'Spain, France, United States' 'Spain, France, Uruguay' 'Spain, Germany'
 'Spain, Germany, Denmark, United States' 'Spain, Italy'
 'Spain, Italy, Argentina' 'Spain, Mexico' 'Spain, Mexico, France'
 'Spain, Portugal' 'Spain, Switzerland' 'Spain, Thailand, United States'
 'Spain, United Kingdom' 'Spain, United Kingdom, United States'
 'Spain, United States' 'Sweden'
 'Sweden, Czech Republic, United Kingdom, Denmark, Netherlands'
 'Sweden, Netherlands' 'Sweden, United Kingdom, Finland'
 'Sweden, United States' 'Switzerland' 'Switzerland, France'
 'Switzerland, France, Belgium, United States'
 'Switzerland, United Kingdom, Australia'
 'Switzerland, United Kingdom, United States' 'Switzerland, United States'
 'Switzerland, Vatican City, Italy, Germany, France'
 'Syria, France, Lebanon, Qatar' 'Taiwan' 'Taiwan, China'
 'Taiwan, China, France, United States'
 'Taiwan, Hong Kong, United States, China' 'Taiwan, Malaysia' 'Thailand'
 'Thailand, Canada, United States' 'Thailand, China, United States'
 'Thailand, United States' 'Turkey' 'Turkey, Azerbaijan'
 'Turkey, France, Germany, Poland' 'Turkey, India' 'Turkey, South Korea'
 'Turkey, United States' 'Ukraine' 'United Arab Emirates'
 'United Arab Emirates, Jordan'
 'United Arab Emirates, Jordan, Lebanon, Saudi Arabia'
 'United Arab Emirates, Romania'
 'United Arab Emirates, United Kingdom, India'
 'United Arab Emirates, United States'
 'United Arab Emirates, United States, United Kingdom' 'United Kingdom'
 'United Kingdom,' 'United Kingdom, Australia'
 'United Kingdom, Australia, Canada, United States'
 'United Kingdom, Australia, France'
 'United Kingdom, Australia, France, United States'
 'United Kingdom, Australia, United States' 'United Kingdom, Belgium'
 'United Kingdom, Belgium, Sweden' 'United Kingdom, Brazil, Germany'
 'United Kingdom, Canada' 'United Kingdom, Canada, France, United States'
 'United Kingdom, Canada, Italy' 'United Kingdom, Canada, Japan'
 'United Kingdom, Canada, United States'
 'United Kingdom, Canada, United States, Cayman Islands'
 'United Kingdom, Canada, United States, Germany' 'United Kingdom, China'
 'United Kingdom, China, United States'
 'United Kingdom, China, United States, India'
 'United Kingdom, Czech Republic, Germany, United States'
 'United Kingdom, Czech Republic, United States, Germany, Bahamas'
 'United Kingdom, Denmark, Canada, Croatia'
 'United Kingdom, Egypt, United States'
 'United Kingdom, Finland, Germany, United States, Australia, Japan, France, Ireland'
 'United Kingdom, France' 'United Kingdom, France, Belgium'
 'United Kingdom, France, Belgium, Canada, United States'
 'United Kingdom, France, Belgium, Ireland, United States'
 'United Kingdom, France, Belgium, United States'
 'United Kingdom, France, Canada, Belgium, United States'
 'United Kingdom, France, Germany'
 'United Kingdom, France, Germany, Spain'
 'United Kingdom, France, Germany, United States'
 'United Kingdom, France, Poland, Germany, United States'
 'United Kingdom, France, Spain, United States'
 'United Kingdom, France, United States'
 'United Kingdom, France, United States, Belgium'
 'United Kingdom, France, United States, Belgium, Luxembourg, China, Germany'
 'United Kingdom, Germany' 'United Kingdom, Germany, Canada'
 'United Kingdom, Germany, Canada, United States'
 'United Kingdom, Germany, France, United States'
 'United Kingdom, Germany, Spain, United States'
 'United Kingdom, Germany, United Arab Emirates, New Zealand'
 'United Kingdom, Germany, United States'
 'United Kingdom, Germany, United States, France'
 'United Kingdom, Hong Kong' 'United Kingdom, Hungary, Australia'
 'United Kingdom, India' 'United Kingdom, India, Sweden'
 'United Kingdom, India, United States' 'United Kingdom, Ireland'
 'United Kingdom, Ireland, United States' 'United Kingdom, Israel, Russia'
 'United Kingdom, Italy'
 'United Kingdom, Italy, Israel, Peru, United States'
 'United Kingdom, Japan' 'United Kingdom, Japan, United States'
 'United Kingdom, Jordan, Qatar, Iran' 'United Kingdom, Kenya'
 'United Kingdom, Lithuania' 'United Kingdom, Malawi'
 'United Kingdom, Namibia, South Africa, Zimbabwe, United States'
 'United Kingdom, New Zealand' 'United Kingdom, Nigeria'
 'United Kingdom, Norway, Denmark, Germany, Sweden'
 'United Kingdom, Pakistan' 'United Kingdom, Poland'
 'United Kingdom, Poland, United States' 'United Kingdom, Russia'
 'United Kingdom, Russia, United States' 'United Kingdom, Singapore'
 'United Kingdom, South Africa'
 'United Kingdom, South Africa, Australia, United States'
 'United Kingdom, South Africa, France' 'United Kingdom, South Korea'
 'United Kingdom, Spain' 'United Kingdom, Spain, Belgium'
 'United Kingdom, Spain, United States'
 'United Kingdom, Spain, United States, Germany'
 'United Kingdom, Thailand' 'United Kingdom, Ukraine, United States'
 'United Kingdom, United States'
 'United Kingdom, United States, Australia'
 'United Kingdom, United States, Canada'
 'United Kingdom, United States, Czech Republic'
 'United Kingdom, United States, Dominican Republic'
 'United Kingdom, United States, France'
 'United Kingdom, United States, France, Germany'
 'United Kingdom, United States, France, Italy'
 'United Kingdom, United States, Germany, Denmark, Belgium, Japan'
 'United Kingdom, United States, Ireland'
 'United Kingdom, United States, Japan'
 'United Kingdom, United States, Morocco'
 'United Kingdom, United States, Spain, Germany, Greece, Canada'
 'United Kingdom, West Germany' 'United States' 'United States,'
 'United States, Argentina' 'United States, Australia'
 'United States, Australia, China' 'United States, Australia, Mexico'
 'United States, Australia, Samoa, United Kingdom'
 'United States, Australia, South Africa, United Kingdom'
 'United States, Belgium, Canada, France'

In [9]:
# Exploración
## Identificación de NaN
for col in df.columns:
    print("Nan x columna [", col, "]:", df[col].isnull().sum())

Nan x columna [ show_id ]: 0
Nan x columna [ type ]: 0
Nan x columna [ title ]: 0
Nan x columna [ director ]: 2634
Nan x columna [ cast ]: 825
Nan x columna [ country ]: 831
Nan x columna [ date_added ]: 10
Nan x columna [ release_year ]: 0
Nan x columna [ rating ]: 4
Nan x columna [ duration ]: 3
Nan x columna [ listed_in ]: 0
Nan x columna [ description ]: 0

In [97]:
df = pd.read_csv("netflix_titles_2021.csv")
df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

### 2. Separar contenidos con duración en minutos y temporadas (duration)

#### Separar usando expresión regular dígito + palabra
#### Opción 1

In [98]:
# Opción 1
df[['duration_unit', 'time_unit']] = df['duration'].str.extract(r'(\d+) (\w+)')
df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,duration_unit,time_unit
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",90,min
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2,Seasons

#### Separar usando split de espacio
#### Opción 2

In [17]:
## https://pandas.pydata.org/docs/user_guide/text.html
splitted_list = df["duration"].str.split(" ")
splitted_list
df["duration_unit 2"] = pd.DataFrame(splitted_list)["duration"].str.get(0)
df["time_unit 2"] = pd.DataFrame(splitted_list)["duration"].str.get(1)
df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,duration_unit,time_unit,Numero,Unidad,duration_unit 2,time_unit 2
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",90,min,90,min,90,min
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2,Seasons,2,Seasons,2,Seasons

#### Opción 3 By Jazmin

In [18]:
df['Numero']=df['duration'].str.extract('(\d+)') # separa la parte numérica
df['Unidad']=df['duration'].str.extract('(\D+)') # separa por Unidades
df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,duration_unit,time_unit,Numero,Unidad,duration_unit 2,time_unit 2
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",90,min,90,min,90,min
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2,Seasons,2,Seasons,2,Seasons

#### Opcion 4 - Oscar

In [19]:
df.insert(df.columns.get_loc('duration')+1, 'unit', '')
df[['duration', 'unit']] = df['duration'].str.split(' ', expand=True)
df['unit'] = df['unit'].str.replace('Seasons', 'Season')

#### Opcion 5 - Manuel

In [27]:
df[['Tiempo','UnidadTiempo']] = df['duration'].str.split(' ', expand=True)
df['UnidadTiempo'] = df['UnidadTiempo'].replace('Seasons', 'Season')
df['Tiempo'] = pd.to_numeric(df['Tiempo'], errors='coerce')
df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,duration_unit,time_unit,Tiempo,UnidadTiempo
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",90,min,90.0,min
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2,Seasons,2.0,Season

#### Opcion 5 - Ricardo

In [35]:
df[['Valor', 'unidad']] = df['duration'].str.split(expand=True)
df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,duration_unit,time_unit,Valor,unidad
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",90,min,90,min
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2,Seasons,2,Seasons

#### Opcion 6 - Joan

In [38]:
df2 = df[['duration','units']] = df.duration.str.split(' ',expand=True)

ValueError: Columns must be same length as key

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   show_id        8807 non-null   object
 1   type           8807 non-null   object
 2   title          8807 non-null   object
 3   director       6173 non-null   object
 4   cast           7982 non-null   object
 5   country        7976 non-null   object
 6   date_added     8797 non-null   object
 7   release_year   8807 non-null   int64
 8   rating         8803 non-null   object
 9   duration       8804 non-null   object
 10  listed_in      8807 non-null   object
 11  description    8807 non-null   object
 12  duration_unit  8804 non-null   object
 13  time_unit      8804 non-null   object
dtypes: int64(1), object(13)
memory usage: 963.4+ KB

In [33]:
# df.dropna(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   show_id        8807 non-null   object
 1   type           8807 non-null   object
 2   title          8807 non-null   object
 3   director       6173 non-null   object
 4   cast           7982 non-null   object
 5   country        7976 non-null   object
 6   date_added     8797 non-null   object
 7   release_year   8807 non-null   int64
 8   rating         8803 non-null   object
 9   duration       8804 non-null   object
 10  listed_in      8807 non-null   object
 11  description    8807 non-null   object
 12  duration_unit  8804 non-null   object
 13  time_unit      8804 non-null   object
dtypes: int64(1), object(13)
memory usage: 963.4+ KB

### 3. Homogenizar para detectar preguntas como:

#### - Tiempo promedio | - Temporadas promedio.

#### ¿Qué situaciones se estén presentando en este caso?

1. Se logra dividir pero tenemos peras y manzanas, por qué? porque hay una dependencia de tipo... ("movies", "TV shows")
2. Las medidas están viciadas, la media no es la media... y así

In [64]:
df["duration_unit"].dropna().astype("int16").describe()

count    8804.000000
mean       69.846888
std        50.814828
min         1.000000
25%         2.000000
50%        88.000000
75%       106.000000
max       312.000000
Name: duration_unit, dtype: float64

In [101]:
df.dropna(subset=["duration_unit"], inplace=True)
df["duration_unit"] = df["duration_unit"].astype("int16")
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8804 entries, 0 to 8806
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   show_id        8804 non-null   object
 1   type           8804 non-null   object
 2   title          8804 non-null   object
 3   director       6170 non-null   object
 4   cast           7979 non-null   object
 5   country        7973 non-null   object
 6   date_added     8794 non-null   object
 7   release_year   8804 non-null   int64
 8   rating         8800 non-null   object
 9   duration       8804 non-null   object
 10  listed_in      8804 non-null   object
 11  description    8804 non-null   object
 12  duration_unit  8804 non-null   int16
 13  time_unit      8804 non-null   object
dtypes: int16(1), int64(1), object(12)
memory usage: 980.1+ KB

* Nótese que los valores se calculan sobre 8804 registros tras el dropna()

In [102]:
## Se observa que no se han eliminado los na y siguyen siendo 8807 registros.
print(df["duration_unit"].isnull().sum()," :|: ",df["duration_unit"].isna().sum())

0  :|:  0

In [103]:
#type(df["duration_unit"].dropna())
#type(df["duration_unit"].dropna(inplace=True))

## Se observa que no se han eliminado los na y siguyen siendo 8807 registros.
print(df["duration_unit"].isnull().sum()," :|: ",df["duration_unit"].isna().sum())

0  :|:  0

In [54]:
df = df.dropna(subset=["duration_unit"])
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8804 entries, 0 to 8806
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   show_id        8804 non-null   object
 1   type           8804 non-null   object
 2   title          8804 non-null   object
 3   director       6170 non-null   object
 4   cast           7979 non-null   object
 5   country        7973 non-null   object
 6   date_added     8794 non-null   object
 7   release_year   8804 non-null   int64
 8   rating         8800 non-null   object
 9   duration       8804 non-null   object
 10  listed_in      8804 non-null   object
 11  description    8804 non-null   object
 12  duration_unit  8804 non-null   int16
 13  time_unit      8804 non-null   object
 14  Valor          8804 non-null   object
 15  unidad         8804 non-null   object
 16  units          8804 non-null   object
dtypes: int16(1), int64(1), object(15)
memory usage: 1.2+ MB

#### Crear una vista de "movies"

Recuerde que la vista y la copia son diferentes la copia es valor, y la vista es referencia

In [104]:
df_movies = df[df["type"] == "Movie"]
df_movies.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,duration_unit,time_unit
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",90,min
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,91,min

#### Crear una vista de "TV Show"

La vista sería válida de cara a realizar agrupaciones u otras operaciones descendentes

In [59]:
df_tv_show = df[df["type"] =="TV Show"]
df_tv_show.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,duration_unit,time_unit,Valor,unidad,units
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2,Seasons,2,Seasons,Seasons
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,1,Season,1,Season,Season

### Operando sobre las vistas

In [62]:
# Cálculo de la media en la columna de duración para las series (TV Show)
serie_duration_mean = df_tv_show.duration_unit.dropna().astype("int16").mean()
print("La medía de duración de una serie es: ", serie_duration_mean,"temporadas", type(serie_duration_mean))

La medía de duración de una serie es:  1.764947683109118 temporadas <class 'numpy.float64'>

In [63]:
# Cálculo de la media en la columna de duración para las películas (Movies)
movie_duration_mean = df_movies.duration_unit.dropna().astype("int16").mean()
print("La medía de duración de una pelicula es: ", movie_duration_mean,"minutos")

La medía de duración de una pelicula es:  99.57718668407311 minutos

In [65]:
df_tv_show.duration_unit.dropna().astype("int16").describe()

count    2676.000000
mean        1.764948
std         1.582752
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max        17.000000
Name: duration_unit, dtype: float64

In [66]:
df_movies.duration_unit.dropna().astype("int16").describe()

count    6128.000000
mean       99.577187
std        28.290593
min         3.000000
25%        87.000000
50%        98.000000
75%       114.000000
max       312.000000
Name: duration_unit, dtype: float64

In [67]:
df_movies = df_movies[ df_movies["duration_unit"].isnull() == False ]
len(df_movies)

6128

# Usando copias

#### Crear una *copia* de "TV Show"

Veamos la diferencia en la media respecto al "combinado"

In [68]:
# las "tv_show" son de tipo seasons
df_tv_show_copy = df.copy()
df_tv_show_copy = df_tv_show_copy[df_tv_show_copy["type"] =="TV Show"]
df_tv_show_copy.dropna(inplace=True)
df_tv_show_copy["duration_unit"].astype('int16').mean()

1.9047619047619047

#### Crear una *copia* de "movies"

Veamos la diferencia en la media respecto al "combinado"

In [105]:
df_movies_copy = df.copy()
df_movies_copy = df_movies_copy[df_movies_copy["type"] =="Movie"]
df_movies_copy.dropna(inplace=True)
df_movies_copy["duration_unit"].astype('int16').mean()

102.70144648023144

### 4. Relación entre listed_in y duration (separado mins y temporadas)

In [106]:
df_movies["listed_in"].nunique()

278

In [107]:
df_movies["duration_unit"].nunique()

205

In [108]:
df_movies["listed_in"]

0                                          Documentaries
6                               Children & Family Movies
7       Dramas, Independent Movies, International Movies
9                                       Comedies, Dramas
12                          Dramas, International Movies
                              ...
8801             Dramas, International Movies, Thrillers
8802                      Cult Movies, Dramas, Thrillers
8804                             Comedies, Horror Movies
8805                  Children & Family Movies, Comedies
8806      Dramas, International Movies, Music & Musicals
Name: listed_in, Length: 6128, dtype: object

In [73]:
listas = df_movies["listed_in"].str.split(",")
listas

0                                         [Documentaries]
6                              [Children & Family Movies]
7       [Dramas,  Independent Movies,  International M...
9                                     [Comedies,  Dramas]
12                        [Dramas,  International Movies]
                              ...
8801          [Dramas,  International Movies,  Thrillers]
8802                   [Cult Movies,  Dramas,  Thrillers]
8804                           [Comedies,  Horror Movies]
8805                [Children & Family Movies,  Comedies]
8806    [Dramas,  International Movies,  Music & Music...
Name: listed_in, Length: 6128, dtype: object

### Opciones para el conteo de categorías

#### Opción 1 - a mano ✊

In [82]:
# Paso 1: Separar todas las categorías en una lista de listas
categorias_listas = df_movies["listed_in"].str.split(",").apply(lambda lista: [categoria.strip() for categoria in lista])
categorias_listas

0                                         [Documentaries]
6                              [Children & Family Movies]
7       [Dramas, Independent Movies, International Mov...
9                                      [Comedies, Dramas]
12                         [Dramas, International Movies]
                              ...
8801            [Dramas, International Movies, Thrillers]
8802                     [Cult Movies, Dramas, Thrillers]
8804                            [Comedies, Horror Movies]
8805                 [Children & Family Movies, Comedies]
8806     [Dramas, International Movies, Music & Musicals]
Name: listed_in, Length: 6128, dtype: object

In [77]:
# Paso 2: Unir todas las listas en una sola lista
todas_categorias = [categoria for lista in categorias_listas for categoria in lista]
todas_categorias

['Documentaries',
 'Children & Family Movies',
 'Dramas',
 'Independent Movies',
 'International Movies',
 'Comedies',
 'Dramas',
 'Dramas',
 'International Movies',
 'Children & Family Movies',
 'Comedies',
 'Documentaries',
 'International Movies',
 'Thrillers',
 'Comedies',
 'International Movies',
 'Children & Family Movies',
 'Comedies',
 'International Movies',
 'Romantic Movies',
 'Comedies',
 'International Movies',
 'Music & Musicals',
 'Comedies',
 'Horror Movies',
 'Sci-Fi & Fantasy',
 'Thrillers',
 'Dramas',
 'Independent Movies',
 'International Movies',
 'Dramas',
 'International Movies',
 'Thrillers',
 'Action & Adventure',
 'Dramas',
 'International Movies',
 'Action & Adventure',
 'Dramas',
 'Action & Adventure',
 'Classic Movies',
 'Dramas',
 'Dramas',
 'Horror Movies',
 'Thrillers',
 'Action & Adventure',
 'Horror Movies',
 'Thrillers',
 'Action & Adventure',
 'Horror Movies',
 'Thrillers',
 'Documentaries',
 'Action & Adventure',
 'Dramas',
 'Thrillers',
 'Action & Adventure',
 'Anime Features',
 'International Movies',
 'Action & Adventure',
 'Anime Features',
 'International Movies',
 'Action & Adventure',
 'Anime Features',
 'International Movies',
 'Action & Adventure',
 'Anime Features',
 'International Movies',
 'Action & Adventure',
 'Anime Features',
 'International Movies',
 'Action & Adventure',
 'Anime Features',
 'International Movies',
 'Action & Adventure',
 'Anime Features',
 'International Movies',
 'Action & Adventure',
 'Anime Features',
 'International Movies',
 'Action & Adventure',
 'Anime Features',
 'International Movies',
 'Action & Adventure',
 'Anime Features',
 'International Movies',
 'Action & Adventure',
 'Anime Features',
 'International Movies',
 'Action & Adventure',
 'Anime Features',
 'International Movies',
 'Children & Family Movies',
 'Documentaries',
 'International Movies',
 'Sports Movies',
 'Children & Family Movies',
 'Dramas',
 'International Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Comedies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Children & Family Movies',
 'Action & Adventure',
 'Action & Adventure',
 'Comedies',
 'Dramas',
 'International Movies',
 'Thrillers',
 'Documentaries',
 'Sports Movies',
 'Sci-Fi & Fantasy',
 'Thrillers',
 'Documentaries',
 'International Movies',
 'Dramas',
 'International Movies',
 'Romantic Movies',
 'Children & Family Movies',
 'Comedies',
 'Documentaries',
 'Music & Musicals',
 'Documentaries',
 'Sports Movies',
 'Dramas',
 'International Movies',
 'Thrillers',
 'Action & Adventure',
 'Comedies',
 'Dramas',
 'Children & Family Movies',
 'Dramas',
 'Dramas',
 'Comedies',
 'Romantic Movies',
 'Dramas',
 'International Movies',
 'Thrillers',
 'Dramas',
 'Romantic Movies',
 'Comedies',
 'Dramas',
 'Independent Movies',
 'Documentaries',
 'Dramas',
 'International Movies',
 'Thrillers',
 'Dramas',
 'International Movies',
 'Romantic Movies',
 'Thrillers',
 'Dramas',
 'International Movies',
 'Romantic Movies',
 'Children & Family Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Thrillers',
 'Dramas',
 'Children & Family Movies',
 'Music & Musicals',
 'Action & Adventure',
 'Classic Movies',
 'Cult Movies',
 'Action & Adventure',
 'Sci-Fi & Fantasy',
 'Action & Adventure',
 'Dramas',
 'Action & Adventure',
 'Dramas',
 'Romantic Movies',
 'Action & Adventure',
 'Comedies',
 'Dramas',
 'Romantic Movies',
 'Classic Movies',
 'Comedies',
 'Dramas',
 'Dramas',
 'International Movies',
 'Thrillers',
 'Action & Adventure',
 'Dramas',
 'Action & Adventure',
 'Sci-Fi & Fantasy',
 'Comedies',
 'Cult Movies',
 'Comedies',
 'Cult Movies',
 'Music & Musicals',
 'Comedies',
 'Music & Musicals',
 'Action & Adventure',
 'Comedies',
 'Thrillers',
 'Action & Adventure',
 'International Movies',
 'Comedies',
 'Action & Adventure',
 'Children & Family Movies',
 'Cult Movies',
 'Comedies',
 'Dramas',
 'Romantic Movies',
 'Sci-Fi & Fantasy',
 'Thrillers',
 'Comedies',
 'Romantic Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Comedies',
 'Cult Movies',
 'Sci-Fi & Fantasy',
 'Dramas',
 'Comedies',
 'Romantic Movies',
 'Action & Adventure',
 'Comedies',
 'Classic Movies',
 'Dramas',
 'Children & Family Movies',
 'Comedies',
 'Action & Adventure',
 'Children & Family Movies',
 'Comedies',
 'Action & Adventure',
 'Dramas',
 'Documentaries',
 'Music & Musicals',
 'Dramas',
 'Faith & Spirituality',
 'Comedies',
 'Music & Musicals',
 'Documentaries',
 'LGBTQ Movies',
 'Action & Adventure',
 'Dramas',
 'Dramas',
 'Romantic Movies',
 'Action & Adventure',
 'Comedies',
 'Action & Adventure',
 'Classic Movies',
 'Action & Adventure',
 'Comedies',
 'Comedies',
 'Romantic Movies',
 'Comedies',
 'Romantic Movies',
 'Comedies',
 'Action & Adventure',
 'Classic Movies',
 'Documentaries',
 'Sports Movies',
 'Comedies',
 'International Movies',
 'Dramas',
 'International Movies',
 'Dramas',
 'Independent Movies',
 'Action & Adventure',
 'Comedies',
 'International Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Comedies',
 'Romantic Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Action & Adventure',
 'Horror Movies',
 'International Movies',
 'Dramas',
 'International Movies',
 'Thrillers',
 'Comedies',
 'International Movies',
 'Music & Musicals',
 'Comedies',
 'International Movies',
 'Comedies',
 'International Movies',
 'Comedies',
 'International Movies',
 'Sci-Fi & Fantasy',
 'Dramas',
 'Independent Movies',
 'International Movies',
 'Action & Adventure',
 'International Movies',
 'Music & Musicals',
 'Dramas',
 'International Movies',
 'Music & Musicals',
 'Dramas',
 'International Movies',
 'Music & Musicals',
 'Horror Movies',
 'International Movies',
 'Horror Movies',
 'International Movies',
 'Action & Adventure',
 'International Movies',
 'Action & Adventure',
 'Dramas',
 'International Movies',
 'Comedies',
 'Dramas',
 'Independent Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Documentaries',
 'Dramas',
 'Independent Movies',
 'Romantic Movies',
 'Action & Adventure',
 'Horror Movies',
 'Documentaries',
 'Sports Movies',
 'Children & Family Movies',
 'Dramas',
 'Documentaries',
 'Music & Musicals',
 'Documentaries',
 'LGBTQ Movies',
 'Sports Movies',
 'Horror Movies',
 'International Movies',
 'Thrillers',
 'Horror Movies',
 'International Movies',
 'Thrillers',
 'Horror Movies',
 'International Movies',
 'Thrillers',
 'Horror Movies',
 'International Movies',
 'Thrillers',
 'Action & Adventure',
 'Anime Features',
 'Dramas',
 'International Movies',
 'Thrillers',
 'Dramas',
 'International Movies',
 'Romantic Movies',
 'Action & Adventure',
 'Dramas',
 'Children & Family Movies',
 'Comedies',
 'Music & Musicals',
 'Dramas',
 'International Movies',
 'Romantic Movies',
 'Dramas',
 'Independent Movies',
 'Romantic Movies',
 'International Movies',
 'Thrillers',
 'Dramas',
 'International Movies',
 'Romantic Movies',
 'Documentaries',
 'International Movies',
 'Dramas',
 'International Movies',
 'Dramas',
 'International Movies',
 'Romantic Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Comedies',
 'International Movies',
 'Romantic Movies',
 'Documentaries',
 'LGBTQ Movies',
 'Sports Movies',
 'Comedies',
 'Independent Movies',
 'Classic Movies',
 'Dramas',
 'Independent Movies',
 'Dramas',
 'International Movies',
 'Action & Adventure',
 'Stand-Up Comedy',
 'Action & Adventure',
 'Anime Features',
 'Children & Family Movies',
 'Comedies',
 'International Movies',
 'Dramas',
 'Independent Movies',
 'International Movies',
 'Documentaries',
 'International Movies',
 'Comedies',
 'Romantic Movies',
 'Dramas',
 'International Movies',
 'Documentaries',
 'Sports Movies',
 'Comedies',
 'Dramas',
 'Independent Movies',
 'Comedies',
 'International Movies',
 'Romantic Movies',
 'International Movies',
 'Music & Musicals',
 'Action & Adventure',
 'Comedies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Horror Movies',
 'Independent Movies',
 'International Movies',
 'Children & Family Movies',
 'Music & Musicals',
 'Action & Adventure',
 'Comedies',
 'International Movies',
 'Documentaries',
 'International Movies',
 'Comedies',
 'Cult Movies',
 'International Movies',
 'Documentaries',
 'Classic Movies',
 'Dramas',
 'International Movies',
 'Dramas',
 'International Movies',
 'Horror Movies',
 'Movies',
 'Dramas',
 'Independent Movies',
 'Romantic Movies',
 'Dramas',
 'International Movies',
 'Documentaries',
 'LGBTQ Movies',
 'Documentaries',
 'International Movies',
 'Children & Family Movies',
 'Comedies',
 'Children & Family Movies',
 'Comedies',
 'Action & Adventure',
 'Sci-Fi & Fantasy',
 'Action & Adventure',
 'Dramas',
 'Children & Family Movies',
 'Comedies',
 'Sci-Fi & Fantasy',
 'Action & Adventure',
 'Horror Movies',
 'Sci-Fi & Fantasy',
 'Classic Movies',
 'Comedies',
 'Cult Movies',
 'Dramas',
 'Romantic Movies',
 'Dramas',
 'Thrillers',
 'Comedies',
 'Romantic Movies',
 'Dramas',
 'Independent Movies',
 'International Movies',
 'Action & Adventure',
 'Sci-Fi & Fantasy',
 'Thrillers',
 'Dramas',
 'Independent Movies',
 'Comedies',
 'Dramas',
 'Children & Family Movies',
 'Comedies',
 'Dramas',
 'Children & Family Movies',
 'Comedies',
 'Action & Adventure',
 'Comedies',
 'Children & Family Movies',
 'Comedies',
 'Sci-Fi & Fantasy',
 'Comedies',
 'Dramas',
 'Sports Movies',
 'Action & Adventure',
 'Dramas',
 'Sci-Fi & Fantasy',
 'Action & Adventure',
 'Comedies',
 'Cult Movies',
 'Comedies',
 'Dramas',
 'Horror Movies',
 'Action & Adventure',
 'Comedies',
 'Dramas',
 'Thrillers',
 'Action & Adventure',
 'Dramas',
 'Independent Movies',
 'Thrillers',
 'Thrillers',
 'Stand-Up Comedy',
 'Comedies',
 'Romantic Movies',
 'Dramas',
 'International Movies',
 'Action & Adventure',
 'International Movies',
 'Thrillers',
 'Dramas',
 'Independent Movies',
 'International Movies',
 'Documentaries',
 'International Movies',
 'Dramas',
 'Independent Movies',
 'International Movies',
 'Action & Adventure',
 'International Movies',
 'Action & Adventure',
 'Comedies',
 'International Movies',
 'Comedies',
 'International Movies',
 'Romantic Movies',
 'Comedies',
 'Romantic Movies',
 'Action & Adventure',
 'International Movies',
 'Documentaries',
 'Action & Adventure',
 'International Movies',
 'Thrillers',
 'Comedies',
 'Dramas',
 'International Movies',
 'Dramas',
 'International Movies',
 'Thrillers',
 'Action & Adventure',
 'Dramas',
 'Children & Family Movies',
 'Sports Movies',
 'Dramas',
 'Independent Movies',
 'International Movies',
 'Comedies',
 'International Movies',
 'Action & Adventure',
 'Horror Movies',
 'International Movies',
 'Horror Movies',
 'International Movies',
 'Thrillers',
 'Dramas',
 'Romantic Movies',
 'Documentaries',
 'Children & Family Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Sports Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Children & Family Movies',
 'Dramas',
 'Comedies',
 'International Movies',
 'Anime Features',
 'Children & Family Movies',
 'International Movies',
 'Dramas',
 'International Movies',
 'Thrillers',
 'Children & Family Movies',
 'Comedies',
 'Dramas',
 'Independent Movies',
 'Dramas',
 'International Movies',
 'Romantic Movies',
 'Action & Adventure',
 'Dramas',
 'International Movies',
 'Romantic Movies',
 'Dramas',
 'International Movies',
 'Thrillers',
 'Horror Movies',
 'LGBTQ Movies',
 'Comedies',
 'International Movies',
 'Dramas',
 'Independent Movies',
 'Thrillers',
 'Dramas',
 'Dramas',
 'Romantic Movies',
 'Dramas',
 'Romantic Movies',
 'Dramas',
 'Romantic Movies',
 'Dramas',
 'Romantic Movies',
 'Action & Adventure',
 'Dramas',
 'Romantic Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Comedies',
 'Cult Movies',
 'Documentaries',
 'International Movies',
 'Music & Musicals',
 'Documentaries',
 'International Movies',
 'Sports Movies',
 'Dramas',
 'International Movies',
 'Romantic Movies',
 'Children & Family Movies',
 'Comedies',
 'Sports Movies',
 'Comedies',
 'Dramas',
 'Independent Movies',
 'Documentaries',
 'Horror Movies',
 'International Movies',
 'Action & Adventure',
 'Comedies',
 'Documentaries',
 'International Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Dramas',
 'Independent Movies',
 'Movies',
 'Children & Family Movies',
 'Dramas',
 'International Movies',
 'Documentaries',
 'Sports Movies',
 'Action & Adventure',
 'Comedies',
 'Stand-Up Comedy',
 'Comedies',
 'Documentaries',
 'International Movies',
 'Horror Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Action & Adventure',
 'Dramas',
 'International Movies',
 'Dramas',
 'International Movies',
 'Romantic Movies',
 'Stand-Up Comedy',
 'Thrillers',
 'Children & Family Movies',
 'Comedies',
 'Sci-Fi & Fantasy',
 'Comedies',
 'International Movies',
 'Comedies',
 'Dramas',
 'Romantic Movies',
 'Dramas',
 'Romantic Movies',
 'Comedies',
 'Music & Musicals',
 'Documentaries',
 'International Movies',
 'Action & Adventure',
 'International Movies',
 'Dramas',
 'International Movies',
 'Action & Adventure',
 'International Movies',
 'Dramas',
 'International Movies',
 'Dramas',
 'International Movies',
 'Romantic Movies',
 'Dramas',
 'International Movies',
 'International Movies',
 'Romantic Movies',
 'Comedies',
 'International Movies',
 'Dramas',
 'International Movies',
 'Dramas',
 'International Movies',
 'Dramas',
 'International Movies',
 'Romantic Movies',
 'Dramas',
 'International Movies',
 'Dramas',
 'International Movies',
 'Dramas',
 'International Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Dramas',
 'International Movies',
 'Horror Movies',
 'LGBTQ Movies',
 'International Movies',
 'Romantic Movies',
 'Thrillers',
 'Comedies',
 'International Movies',
 'Dramas',
 'International Movies',
 'Thrillers',
 'Action & Adventure',
 'Cult Movies',
 'International Movies',
 'Horror Movies',
 'International Movies',
 'Thrillers',
 'Horror Movies',
 'Sci-Fi & Fantasy',
 'Action & Adventure',
 'Action & Adventure',
 'Documentaries',
 'Sports Movies',
 'Action & Adventure',
 'Comedies',
 'Comedies',
 'Action & Adventure',
 'Comedies',
 'Sci-Fi & Fantasy',
 'Comedies',
 'Dramas',
 'Independent Movies',
 'Action & Adventure',
 'Comedies',
 'Action & Adventure',
 'Thrillers',
 'Children & Family Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Romantic Movies',
 'Action & Adventure',
 'International Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Children & Family Movies',
 'Comedies',
 'Children & Family Movies',
 'Comedies',
 'Comedies',
 'Dramas',
 'Romantic Movies',
 'Dramas',
 'Faith & Spirituality',
 'International Movies',
 'Dramas',
 'Romantic Movies',
 'Action & Adventure',
 'Classic Movies',
 'Comedies',
 'Action & Adventure',
 'Anime Features',
 'International Movies',
 'Action & Adventure',
 'Sci-Fi & Fantasy',
 'Comedies',
 'Dramas',
 'Comedies',
 'Romantic Movies',
 'Comedies',
 'Dramas',
 'Romantic Movies',
 'Horror Movies',
 'Dramas',
 'International Movies',
 'Dramas',
 'Romantic Movies',
 'Comedies',
 'Romantic Movies',
 'Children & Family Movies',
 'Comedies',
 'Action & Adventure',
 'Sci-Fi & Fantasy',
 'Children & Family Movies',
 'Comedies',
 'Comedies',
 'Dramas',
 'Independent Movies',
 'Action & Adventure',
 'Comedies',
 'Sports Movies',
 'Dramas',
 'Thrillers',
 'Dramas',
 'Thrillers',
 'Action & Adventure',
 'Children & Family Movies',
 'Classic Movies',
 'Action & Adventure',
 'Children & Family Movies',
 'Dramas',
 'Children & Family Movies',
 'Dramas',
 'Dramas',
 'Action & Adventure',
 'Dramas',
 'International Movies',
 'Horror Movies',
 'Thrillers',
 'Action & Adventure',
 'Action & Adventure',
 'Romantic Movies',
 'Action & Adventure',
 'Horror Movies',
 'Sci-Fi & Fantasy',
 'Action & Adventure',
 'Horror Movies',
 'Sci-Fi & Fantasy',
 'Action & Adventure',
 'Horror Movies',
 'Sci-Fi & Fantasy',
 'Dramas',
 'International Movies',
 'Thrillers',
 'Dramas',
 'Romantic Movies',
 'Sci-Fi & Fantasy',
 'Dramas',
 'Music & Musicals',
 'Romantic Movies',
 'Dramas',
 'Action & Adventure',
 'Comedies',
 'Dramas',
 'International Movies',
 'Thrillers',
 'Comedies',
 'Dramas',
 'International Movies',
 'Dramas',
 'International Movies',
 'Thrillers',
 'Dramas',
 'International Movies',
 'Dramas',
 'Comedies',
 'International Movies',
 'Dramas',
 'Independent Movies',
 'International Movies',
 'Documentaries',
 'International Movies',
 'Dramas',
 'International Movies',
 'Action & Adventure',
 'Documentaries',
 'Sports Movies',
 'Horror Movies',
 'Comedies',
 'Romantic Movies',
 'Documentaries',
 'International Movies',
 'Comedies',
 'International Movies',
 'Music & Musicals',
 'Dramas',
 'International Movies',
 'Romantic Movies',
 'Dramas',
 'International Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'International Movies',
 'Music & Musicals',
 'Romantic Movies',
 'Action & Adventure',
 'Anime Features',
 'International Movies',
 'Action & Adventure',
 'Anime Features',
 'International Movies',
 'Action & Adventure',
 'Anime Features',
 'International Movies',
 'Dramas',
 'International Movies',
 'Dramas',
 'Action & Adventure',
 'Dramas',
 'International Movies',
 'Comedies',
 'International Movies',
 'Romantic Movies',
 'Action & Adventure',
 'Anime Features',
 'Classic Movies',
 'Action & Adventure',
 'International Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Comedies',
 'Dramas',
 'Independent Movies',
 'Dramas',
 'International Movies',
 'Dramas',
 'Independent Movies',
 'International Movies',
 'Dramas',
 'Comedies',
 'Dramas',
 'Independent Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Documentaries',
 'International Movies',
 'Sports Movies',
 'Dramas',
 'Independent Movies',
 'Dramas',
 'International Movies',
 'Thrillers',
 'Action & Adventure',
 'Dramas',
 'International Movies',
 'Documentaries',
 'Documentaries',
 'Comedies',
 'Independent Movies',
 'Action & Adventure',
 'Documentaries',
 'Documentaries',
 'Documentaries',
 'Horror Movies',
 'Movies',
 'Movies',
 'Movies',
 'Comedies',
 'Dramas',
 'International Movies',
 'Children & Family Movies',
 'Dramas',
 ...]

In [80]:
# Paso 3: Obtener los elementos únicos (usando un conjunto ---> no soporta repetidos)
elementos_unicos = set(todas_categorias)
elementos_unicos

{'Action & Adventure',
 'Anime Features',
 'Children & Family Movies',
 'Classic Movies',
 'Comedies',
 'Cult Movies',
 'Documentaries',
 'Dramas',
 'Faith & Spirituality',
 'Horror Movies',
 'Independent Movies',
 'International Movies',
 'LGBTQ Movies',
 'Movies',
 'Music & Musicals',
 'Romantic Movies',
 'Sci-Fi & Fantasy',
 'Sports Movies',
 'Stand-Up Comedy',
 'Thrillers'}

In [81]:
print(elementos_unicos, len(elementos_unicos))

{'Horror Movies', 'LGBTQ Movies', 'Comedies', 'Romantic Movies', 'Independent Movies', 'Movies', 'Anime Features', 'Stand-Up Comedy', 'Sports Movies', 'Action & Adventure', 'Dramas', 'Children & Family Movies', 'Cult Movies', 'Faith & Spirituality', 'Music & Musicals', 'Sci-Fi & Fantasy', 'Classic Movies', 'Documentaries', 'Thrillers', 'International Movies'} 20

#### Opción 2 - con la magia de la librería 🧙‍♂️

In [86]:
# Paso 1: Separar todas las categorías en una única lista
listado_categorias = categorias_listas.explode()
listado_categorias

0                  Documentaries
6       Children & Family Movies
7                         Dramas
7             Independent Movies
7           International Movies
                  ...
8805    Children & Family Movies
8805                    Comedies
8806                      Dramas
8806        International Movies
8806            Music & Musicals
Name: listed_in, Length: 13187, dtype: object

In [87]:
# Paso 2: realizar el conteo
cantidad_por_categoria = listado_categorias.value_counts()

In [89]:
# Paso 3: visualizar
cantidad_por_categoria

International Movies        2752
Dramas                      2427
Comedies                    1674
Documentaries                869
Action & Adventure           859
Independent Movies           756
Children & Family Movies     641
Romantic Movies              616
Thrillers                    577
Music & Musicals             375
Horror Movies                357
Stand-Up Comedy              343
Sci-Fi & Fantasy             243
Sports Movies                219
Classic Movies               116
LGBTQ Movies                 102
Cult Movies                   71
Anime Features                71
Faith & Spirituality          65
Movies                        54
Name: listed_in, dtype: int64

In [109]:
df_movies_by_listin = df_movies[ df_movies["listed_in"].str.contains("Music & Musicals") ]
df_movies_by_listin.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 375 entries, 26 to 8806
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   show_id        375 non-null    object
 1   type           375 non-null    object
 2   title          375 non-null    object
 3   director       358 non-null    object
 4   cast           340 non-null    object
 5   country        328 non-null    object
 6   date_added     375 non-null    object
 7   release_year   375 non-null    int64
 8   rating         375 non-null    object
 9   duration       375 non-null    object
 10  listed_in      375 non-null    object
 11  description    375 non-null    object
 12  duration_unit  375 non-null    int16
 13  time_unit      375 non-null    object
dtypes: int16(1), int64(1), object(12)
memory usage: 41.7+ KB

In [110]:
print("El tiempo promedio de una pelicula en la categoría es:" , int(df_movies_by_listin["duration_unit"].dropna().astype('int16').mean()), "minutos")

El tiempo promedio de una pelicula en la categoría es: 106 minutos

## 5. Frecuencia de distribución de los paises

In [115]:
df.country.isnull().sum()

831

In [117]:
df.dropna(subset=["country"], inplace=True)
df.country.isnull().sum()

0

In [119]:
# Paso 1: Separar todos los paises en una única lista
listado_paises = df["country"].str.split(", ").explode()
listado_paises

0       United States
1        South Africa
4               India
7       United States
7               Ghana
            ...
8801           Jordan
8802    United States
8804    United States
8805    United States
8806            India
Name: country, Length: 10014, dtype: object

In [120]:
# Paso 2: realizar el conteo
cantidad_por_pais = listado_paises.value_counts()

# Paso 3: visualizar
cantidad_por_pais

United States     3689
India             1046
United Kingdom     804
Canada             445
France             393
                  ...
Mongolia             1
Albania              1
Samoa                1
Palestine            1
Bahamas              1
Name: country, Length: 127, dtype: int64

### 6. Actores principales por pais

In [121]:
# Paso 1: Separar todos los actores en una única lista
Listado_actores = df["cast"].str.split(", ").explode()

# Paso 2: realizar el conteo
cantidad_actor = Listado_actores.value_counts()

# Paso 3: visualizar
cantidad_actor

Anupam Kher          43
Shah Rukh Khan       34
Naseeruddin Shah     31
Akshay Kumar         30
Om Puri              30
                     ..
Kunika                1
Da Peng               1
Marta Marco           1
Ruangroj Prachaya     1
Eve Arden             1
Name: cast, Length: 34321, dtype: int64

In [122]:
Listado_paises = Listado_paises.str.replace(",","")
listado_paises_unicos = list(set(Listado_paises))

In [123]:
listado_paises_unicos.sort()
listado_paises_unicos

['',
 'Afghanistan',
 'Albania',
 'Algeria',
 'Angola',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bangladesh',
 'Belarus',
 'Belgium',
 'Bermuda',
 'Botswana',
 'Brazil',
 'Bulgaria',
 'Burkina Faso',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cayman Islands',
 'Chile',
 'China',
 'Colombia',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Dominican Republic',
 'East Germany',
 'Ecuador',
 'Egypt',
 'Ethiopia',
 'Finland',
 'France',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Guatemala',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kuwait',
 'Latvia',
 'Lebanon',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Malawi',
 'Malaysia',
 'Malta',
 'Mauritius',
 'Mexico',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Nigeria',
 'Norway',
 'Pakistan',
 'Palestine',
 'Panama',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Romania',
 'Russia',
 'Samoa',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Somalia',
 'South Africa',
 'South Korea',
 'Soviet Union',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Thailand',
 'Turkey',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Vatican City',
 'Venezuela',
 'Vietnam',
 'West Germany',
 'Zimbabwe']

In [ ]:
### ------------------

In [124]:
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
df = pd.read_csv("netflix_titles_2021.csv")
df.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

In [126]:
import pandas as pd
from collections import Counter

# Ejemplo de DataFrame
data = {
    'show_id': [1, 2, 3, 4, 5],
    'type': ['Movie', 'Movie', 'Movie', 'TV Show', 'Movie'],
    'title': ['Movie 1', 'Movie 2', 'Movie 3', 'TV Show 1', 'Movie 4'],
    'director': ['Director 1', 'Director 2', 'Director 3', 'Director 4', 'Director 5'],
    'cast': ['Actor A, Actor B', 'Actor B, Actor C', 'Actor A, Actor C', 'Actor D, Actor E', 'Actor B, Actor E'],
    'country': ['Country 1, Country 2', 'Country 2', 'Country 1', 'Country 3', 'Country 2, Country 3']
}

df = pd.DataFrame(data)

# Paso 1: Convertir las celdas separadas por comas en registros individuales
df['country'] = df['country'].str.split(', ')

# Paso 2: Utilizar explode() en la columna "country"
df_exploded = df.explode('country')

# Paso 3: Agrupar por país y contar los actores
grouped = df_exploded.groupby('country')['cast'].apply(lambda x: ','.join(x)).str.split(',')
actor_counts_by_country = grouped.apply(lambda x: Counter(x))

# Paso 4: Obtener el actor con más repeticiones por país
most_common_actors_by_country = actor_counts_by_country.apply(lambda x: x.most_common(1)[0][0])

print(most_common_actors_by_country)

country
Country 1     Actor A
Country 2     Actor B
Country 3     Actor E
Name: cast, dtype: object